import type { Metadata } from 'next';
import { Articles } from '../../components/news/Articles';

export const metadata: Metadata = {
  title: 'News sample app｜Create Next App',
  description: 'Generated by create next app',
};

export default async function Page() {
  const API = process.env.API_KEY;
  const res = await fetch(`https://newsapi.org/v2/top-headlines?country=jp&pageSize=5&apiKey=${API}`);
  const json = await res.json();
  const articles = json?.articles;

  return (
    <section>
      <h1 className="text-3xl">news sample app</h1>
      <Articles articles={articles} />
    </section>
  );
}
